### ISSUE TITLE
在微调llama时出现错误

### ISSUE THREAD

**Issue by Qu1n-22** [wuyike2000/Retrieve-Rewrite-Answer#4]
以下是具体的报错内容，我运行代码前仅修改了os.environ["CUDA_VISIBLE_DEVICES"] = "0"，是不支持单卡微调吗？

```
Traceback (most recent call last):
  File "/public2/home/wangchen/Retrieve-Rewrite-Answer-main/finetune-llama/run_clm_sft_with_peft-7b.py", line 419, in <module>
    main()
  File "/public2/home/wangchen/Retrieve-Rewrite-Answer-main/finetune-llama/run_clm_sft_with_peft-7b.py", line 392, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1904, in _inner_training_loop
    self.accelerator.clip_grad_norm_(
  File "/public2/home/wangchen/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 1893, in clip_grad_norm_
    self.unscale_gradients()
  File "/public2/home/wangchen/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 1856, in unscale_gradients
    self.scaler.unscale_(opt)
  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 307, in unscale_
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(
  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 229, in _unscale_grads_
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.
```

以及在双卡正常训练，未修改代码，进度达到epoch=1.0时似乎无法保存，

```
353 [INFO|trainer.py:3160] 2023-12-03 12:44:05,389 >>   Num examples = 1386
354 [INFO|trainer.py:3163] 2023-12-03 12:44:05,389 >>   Batch size = 4
355   File "/public2/home/wangchen/Retrieve-Rewrite-Answer-main/finetune-llama/run_clm_sft_with_peft-7b.py", line 419, in <module>
356 {'eval_loss': 0.13147063553333282, 'eval_runtime': 72.5555, 'eval_samples_per_second': 19.103, 'eval_steps_per_second': 2.398, 'epoch': 1.0}
357     main()
358   File "/public2/home/wangchen/Retrieve-Rewrite-Answer-main/finetune-llama/run_clm_sft_with_peft-7b.py", line 392, in main
359     train_result = trainer.train(resume_from_checkpoint=checkpoint)
360   File "/public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
361     return inner_training_loop(
362   File "/public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1937, in _inner_training_loop
363     self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
364   File "/public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2282, in _maybe_log_save_evaluate
365     self._save_checkpoint(model, trial, metrics=metrics)
366   File "/public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2350, in _save_checkpoint
367     self.save_model(output_dir, _internal_call=True)
368   File "/public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2826, in save_model
369     raise ValueError("Install Accelerate from main branch")
370 ValueError: Install Accelerate from main branch
371 ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
372 │ /public2/home/wangchen/Retrieve-Rewrite-Answer-main/finetune-llama/run_clm_sft_with_peft-7b.py:4 │
373 │ 19 in <module>                                                                                   │
374 │                                                                                                  │
375 │   416                                                                                            │
376 │   417                                                                                            │
377 │   418 if __name__ == "__main__":                                                                 │
378 │ ❱ 419 │   main()                                                                                 │
379 │   420                                                                                            │
380 │                                                                                                  │
381 │ /public2/home/wangchen/Retrieve-Rewrite-Answer-main/finetune-llama/run_clm_sft_with_peft-7b.py:3 │
382 │ 92 in main                                                                                       │
383 │                                                                                                  │
384 │   389 │   │   │   checkpoint = training_args.resume_from_checkpoint                              │
385 │   390 │   │   elif last_checkpoint is not None:                                                  │
386 │   391 │   │   │   checkpoint = last_checkpoint                                                   │
387 │ ❱ 392 │   │   train_result = trainer.train(resume_from_checkpoint=checkpoint)                    │
388 │   393 │   │                                                                                      │
389 │   394 │   │   metrics = train_result.metrics                                                     │
390 │   395                                                                                            │
391 │                                                                                                  │
392 │ /public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py:1555 in train │
393 │                                                                                                  │
394 │   1552 │   │   │   finally:                                                                      │
395 │   1553 │   │   │   │   hf_hub_utils.enable_progress_bars()                                       │
396 │   1554 │   │   else:                                                                             │
397 │ ❱ 1555 │   │   │   return inner_training_loop(                                                   │
398 │   1556 │   │   │   │   args=args,                                                                │
399 │   1557 │   │   │   │   resume_from_checkpoint=resume_from_checkpoint,                            │
400 │   1558 │   │   │   │   trial=trial,                                                              │
401 │                                                                                                  │
402 │ /public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py:1937 in       │
403 │ _inner_training_loop                                                                             │
404 │                                                                                                  │
405 │   1934 │   │   │   │   self.control.should_training_stop = True                                  │
406 │   1935 │   │   │                                                                                 │
407 │   1936 │   │   │   self.control = self.callback_handler.on_epoch_end(args, self.state, self.con  │
408 │ ❱ 1937 │   │   │   self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_  │
409 │   1938 │   │   │                                                                                 │
410 │   1939 │   │   │   if DebugOption.TPU_METRICS_DEBUG in self.args.debug:                          │
411 │   1940 │   │   │   │   if is_torch_tpu_available():                                              │
412 │                                                                                                  │
413 │ /public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py:2282 in       │
414 │ _maybe_log_save_evaluate                                                                         │
415 │                                                                                                  │
416 │   2279 │   │   │   │   self.lr_scheduler.step(metrics[metric_to_check])                          │
417 │   2280 │   │                                                                                     │
418 │   2281 │   │   if self.control.should_save:                                                      │
419 │ ❱ 2282 │   │   │   self._save_checkpoint(model, trial, metrics=metrics)                          │
420 │   2283 │   │   │   self.control = self.callback_handler.on_save(self.args, self.state, self.con  │
421 │   2284 │                                                                                         │
422 │   2285 │   def _load_rng_state(self, checkpoint):                                                │
423 │                                                                                                  │
424 │ /public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py:2350 in       │
425 │ _save_checkpoint                                                                                 │
426 │                                                                                                  │
427 │   2347 │   │                                                                                     │
428 │   2348 │   │   run_dir = self._get_output_dir(trial=trial)                                       │
429 │   2349 │   │   output_dir = os.path.join(run_dir, checkpoint_folder)                             │
430 │ ❱ 2350 │   │   self.save_model(output_dir, _internal_call=True)                                  │
431 │   2351 │   │   if self.is_deepspeed_enabled:                                                     │
432 │   2352 │   │   │   # under zero3 model file itself doesn't get saved since it's bogus! Unless d  │
433 │   2353 │   │   │   # config `stage3_gather_16bit_weights_on_model_save` is True                  │
434 │                                                                                                  │
435 │ /public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py:2826 in       │
436 │ save_model                                                                                       │
437 │                                                                                                  │
438 │   2823 │   │   elif self.is_deepspeed_enabled:                                                   │
439 │   2824 │   │   │   # this takes care of everything as long as we aren't under zero3              │
440 │   2825 │   │   │   if version.parse(accelerate_version) <= version.parse("0.20.3"):              │
441 │ ❱ 2826 │   │   │   │   raise ValueError("Install Accelerate from main branch")                   │
442 │   2827 │   │   │   try:                                                                          │
443 │   2828 │   │   │   │   state_dict = self.accelerator.get_state_dict(self.deepspeed)              │
444 │   2829 │   │   │   │   if self.args.should_save:                                                 │
445 ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
446 ValueError: Install Accelerate from main branch
```

**Comment by wuyike2000** [comment]
第一个问题你看看是不是没有同步修改run_sft_chat-7b.sh的--nproc_per_node，这个对应的参数是使用的显卡数。如果用一张显卡，应修改为torchrun --master_port 29501 --nnodes 1 --nproc_per_node 1 run_clm_sft_with_peft-7b.py。第二个问题应该是没有安装accelerate库函数。

**Comment by Qu1n-22** [comment]
第一个修改好了 但是 第二个还是不行 我库检查了一遍都安装了
在运行epoch=1.0结束，eval结束，好像没办法保存模型，进不到下一个epoch

--更新好像是我的版本有问题，不过我这里的服务器代理似乎出了问题，我下午更新下包再试一下
```
{'loss': 0.1214, 'learning_rate': 9.878532888862671e-05, 'epoch': 0.99}                                                                                                                                      
{'loss': 0.1814, 'learning_rate': 9.877391685355164e-05, 'epoch': 1.0}                                                                                                                                       
 10%|████████████████                                                                                                                                                 | 3110/31160 [58:50<9:13:37,  1.18s/it][2023-12-05 02:53:07,211] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 131072, reducing to 65536
 10%|████████████████                                                                                                                                                 | 3116/31160 [58:56<7:51:47,  1.01s/it][INFO|trainer.py:3158] 2023-12-05 02:53:12,734 >> ***** Running Evaluation *****
[INFO|trainer.py:3160] 2023-12-05 02:53:12,734 >>   Num examples = 1386
[INFO|trainer.py:3163] 2023-12-05 02:53:12,734 >>   Batch size = 4
{'eval_loss': 0.1332675814628601, 'eval_runtime': 72.742, 'eval_samples_per_second': 19.054, 'eval_steps_per_second': 2.392, 'epoch': 1.0}                                                                   
 10%|███████████████▉                                                                                                                                               | 3116/31160 [1:00:09<7:51:47,  1.01s/it╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮                                                                                                          
│ /public2/home/wangchen/Retrieve-Rewrite-Answer-main/finetune-llama/r1un_clm_sft_with_peft-7b.py: │
│ 420 in <module>                                                                                  │
│                                                                                                  │
│   417                                                                                            │
│   418                                                                                            │
│   419 if __name__ == "__main__":                                                                 │
│ ❱ 420 │   main()                                                                                 │
│   421                                                                                            │
│                                                                                                  │
│ /public2/home/wangchen/Retrieve-Rewrite-Answer-main/finetune-llama/r1un_clm_sft_with_peft-7b.py: │
│ 393 in main                                                                                      │
│                                                                                                  │
│   390 │   │   │   checkpoint = training_args.resume_from_checkpoint                              │
│   391 │   │   elif last_checkpoint is not None:                                                  │
│   392 │   │   │   checkpoint = last_checkpoint                                                   │
│ ❱ 393 │   │   train_result = trainer.train(resume_from_checkpoint=checkpoint)                    │
│   394 │   │                                                                                      │
│   395 │   │   metrics = train_result.metrics                                                     │
│   396                                                                                            │
│                                                                                                  │
│ /public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py:1555 in train │
│                                                                                                  │
│   1552 │   │   │   finally:                                                                      │
│   1553 │   │   │   │   hf_hub_utils.enable_progress_bars()                                       │
│   1554 │   │   else:                                                                             │
│ ❱ 1555 │   │   │   return inner_training_loop(                                                   │
│   1556 │   │   │   │   args=args,                                                                │
│   1557 │   │   │   │   resume_from_checkpoint=resume_from_checkpoint,                            │
│   1558 │   │   │   │   trial=trial,                                                              │
│                                                                                                  │
│ /public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py:1937 in       │
│ _inner_training_loop                                                                             │
│                                                                                                  │
│   1934 │   │   │   │   self.control.should_training_stop = True                                  │
│   1935 │   │   │                                                                                 │
│   1936 │   │   │   self.control = self.callback_handler.on_epoch_end(args, self.state, self.con  │
│ ❱ 1937 │   │   │   self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_  │
│   1938 │   │   │                                                                                 │
│   1939 │   │   │   if DebugOption.TPU_METRICS_DEBUG in self.args.debug:                          │
│   1940 │   │   │   │   if is_torch_tpu_available():                                              │
│                                                                                                  │
│ /public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py:2282 in       │
│ _maybe_log_save_evaluate                                                                         │
│                                                                                                  │
│   2279 │   │   │   │   self.lr_scheduler.step(metrics[metric_to_check])                          │
│   2280 │   │                                                                                     │
│   2281 │   │   if self.control.should_save:                                                      │
│ �� 2282 │   │   │   self._save_checkpoint(model, trial, metrics=metrics)                          │
│   2283 │   │   │   self.control = self.callback_handler.on_save(self.args, self.state, self.con  │
│   2284 │                                                                                         │
│   2285 │   def _load_rng_state(self, checkpoint):                                                │
│                                                                                                  │
│ /public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py:2350 in       │
│ _save_checkpoint                                                                                 │
│                                                                                                  │
│   2347 │   │                                                                                     │
│   2348 │   │   run_dir = self._get_output_dir(trial=trial)                                       │
│   2349 │   │   output_dir = os.path.join(run_dir, checkpoint_folder)                             │
│ ❱ 2350 │   │   self.save_model(output_dir, _internal_call=True)                                  │
│   2351 │   │   if self.is_deepspeed_enabled:                                                     │
│   2352 │   │   │   # under zero3 model file itself doesn't get saved since it's bogus! Unless d  │
│   2353 │   │   │   # config `stage3_gather_16bit_weights_on_model_save` is True                  │
│                                                                                                  │
│ /public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py:2826 in       │
│ save_model                                                                                       │
│                                                                                                  │
│   2823 │   │   elif self.is_deepspeed_enabled:                                                   │
│   2824 │   │   │   # this takes care of everything as long as we aren't under zero3              │
│   2825 │   │   │   if version.parse(accelerate_version) <= version.parse("0.20.3"):              │
│ ❱ 2826 │   │   │   │   raise ValueError("Install Accelerate from main branch")                   │
│   2827 │   │   │   try:                                                                          │
│   2828 │   │   │   │   state_dict = self.accelerator.get_state_dict(self.deepspeed)              │
│   2829 │   │   │   │   if self.args.should_save:                                                 │
╰───────────────────────────────────────��──────────────────────────────────────────────────────────╯
ValueError: Install Accelerate from main branch
 10%|███████████████▉                                                                                                                                               | 3116/31160 [1:00:11<9:01:43,  1.16s/it]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /public2/home/wangchen/Retrieve-Rewrite-Answer-main/finetune-llama/r1un_clm_sft_with_peft-7b.py: │
│ 420 in <module>                                                                                  │
│                                                                                                  │
│   417                                                                                            │
│   418                                                                                            │
│   419 if __name__ == "__main__":                                                                 │
│ ❱ 420 │   main()                                                                                 │
│   421                                                                                            │
│                                                                                                  │
│ /public2/home/wangchen/Retrieve-Rewrite-Answer-main/finetune-llama/r1un_clm_sft_with_peft-7b.py: │
│ 393 in main                                                                                      │
│                                                                                                  │
│   390 │   │   │   checkpoint = training_args.resume_from_checkpoint                              │
│   391 │   │   elif last_checkpoint is not None:                                                  │
│   392 │   │   │   checkpoint = last_checkpoint                                                   │
│ ❱ 393 │   │   train_result = trainer.train(resume_from_checkpoint=checkpoint)                    │
│   394 │   │                                                                                      │
│   395 │   │   metrics = train_result.metrics                                                     │
│   396                                                                                            │
│                                                                                                  │
│ /public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py:1555 in train │
│                                                                                                  │
│   1552 │   │   │   finally:                                                                      │
│   1553 │   │   │   │   hf_hub_utils.enable_progress_bars()                                       │
│   1554 │   │   else:                                                                             │
│ ❱ 1555 │   │   │   return inner_training_loop(                                                   │
│   1556 │   │   │   │   args=args,                                                                │
│   1557 │   │   │   │   resume_from_checkpoint=resume_from_checkpoint,                            │
│   1558 │   │   │   │   trial=trial,                                                              │
│                                                                                                  │
│ /public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py:1937 in       │
│ _inner_training_loop                                                                             │
│                                                                                                  │
│   1934 │   │   │   │   self.control.should_training_stop = True                                  │
│   1935 │   │   │                                                                                 │
│   1936 │   │   │   self.control = self.callback_handler.on_epoch_end(args, self.state, self.con  │
│ ❱ 1937 │   │   │   self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_  │
│   1938 │   │   │                                                                                 │
│   1939 │   │   │   if DebugOption.TPU_METRICS_DEBUG in self.args.debug:                          │
│   1940 │   │   │   │   if is_torch_tpu_available():                                              │
│                                                                                                  │
│ /public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py:2282 in       │
│ _maybe_log_save_evaluate                                                                         │
│                                                                                                  │
│   2279 │   │   │   │   self.lr_scheduler.step(metrics[metric_to_check])                          │
│   2280 │   │                                                                                     │
│   2281 │   │   if self.control.should_save:                                                      │
│ �� 2282 │   │   │   self._save_checkpoint(model, trial, metrics=metrics)                          │
│   2283 │   │   │   self.control = self.callback_handler.on_save(self.args, self.state, self.con  │
│   2284 │                                                                                         │
│   2285 │   def _load_rng_state(self, checkpoint):                                                │
│                                                                                                  │
│ /public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py:2350 in       │
│ _save_checkpoint                                                                                 │
│                                                                                                  │
│   2347 │   │                                                                                     │
│   2348 │   │   run_dir = self._get_output_dir(trial=trial)                                       │
│   2349 │   │   output_dir = os.path.join(run_dir, checkpoint_folder)                             │
│ ❱ 2350 │   │   self.save_model(output_dir, _internal_call=True)                                  │
│   2351 │   │   if self.is_deepspeed_enabled:                                                     │
│   2352 │   │   │   # under zero3 model file itself doesn't get saved since it's bogus! Unless d  │
│   2353 │   │   │   # config `stage3_gather_16bit_weights_on_model_save` is True                  │
│                                                                                                  │
│ /public2/home/wangchen/.local/lib/python3.10/site-packages/transformers/trainer.py:2826 in       │
│ save_model                                                                                       │
│                                                                                                  │
│   2823 │   │   elif self.is_deepspeed_enabled:                                                   │
│   2824 │   │   │   # this takes care of everything as long as we aren't under zero3              │
│   2825 │   │   │   if version.parse(accelerate_version) <= version.parse("0.20.3"):              │
│ ❱ 2826 │   │   │   │   raise ValueError("Install Accelerate from main branch")                   │
│   2827 │   │   │   try:                                                                          │
│   2828 │   │   │   │   state_dict = self.accelerator.get_state_dict(self.deepspeed)              │
│   2829 │   │   │   │   if self.args.should_save:                                                 │
╰───────────────────────────────────────��──────────────────────────────────────────────────────────╯
ValueError: Install Accelerate from main branch
[2023-12-05 02:54:31,504] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 282) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.0', 'console_scripts', 'torchrun')())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
r1un_clm_sft_with_peft-7b.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-12-05_02:54:31
  host      : f2f95c9fe8e5
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 283)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-12-05_02:54:31
  host      : f2f95c9fe8e5
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 282)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
wangchen@f2f95c9fe8e5:~/Retrieve-Rewrite-Answer-main/finetune-llama$ ~
```

**Comment by Qu1n-22** [comment]
> 第一个问题你看看是不是没有同步修改run_sft_chat-7b.sh的--nproc_per_node，这个对应的参数是使用的显卡数。如果用一张显卡，应修改为torchrun --master_port 29501 --nnodes 1 --nproc_per_node 1 run_clm_sft_with_peft-7b.py。第二个问题应该是没有安装accelerate库函数。

确实是accelerate的原因，版本不对

**Comment by Yclock** [comment]
> > 第一个问题你看看是不是没有同步修改run_sft_chat-7b.sh的--nproc_per_node，这个对应的参数是使用的显卡数。如果用一张显卡，应修改为torchrun --master_port 29501 --nnodes 1 --nproc_per_node 1 run_clm_sft_with_peft-7b.py。第二个问题应该是没有安装accelerate库函数。
> 
> 确实是accelerate的原因，版本不对

你好，你做微调时内存占用了多少可以告诉我吗？我用4090微调7b，batch_size修改为1仍然内存溢出。
