### ISSUE TITLE
在运行run_clm_sft_with_peft-7b.py文件时，报错缺少文件：FileNotFoundError: [Errno 2] No such file or directory: _dir_dev_json_default-2995dd276f7112c1_0.0.0_8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96.lock'

### ISSUE THREAD

**Issue by Suiji12** [wuyike2000/Retrieve-Rewrite-Answer#6]
01/21/2024 15:27:00 - INFO - __main__ - Training files: D:\jjx\Retrieve-Rewrite-Answer-main\Retrieve-Rewrite-Answer-main\finetune-llama\MetaQA\dataset_dir\dev.json D:\jjx\Retrieve-Rewrite-Answer-main\Retrieve-Rewrite-Answer-main\finetune-llama\MetaQA\dataset_dir\train.json
01/21/2024 15:27:00 - WARNING - root - building dataset...
Using custom data configuration default-2995dd276f7112c1
Loading Dataset Infos from C:\Users\jiaojiaxing\.conda\envs\RRA\lib\site-packages\datasets\packaged_modules\json
Traceback (most recent call last):
  File "D:\jjx\Retrieve-Rewrite-Answer-main\Retrieve-Rewrite-Answer-main\finetune-llama\run_clm_sft_with_peft-7b.py", line 429, in <module>
    main()
  File "D:\jjx\Retrieve-Rewrite-Answer-main\Retrieve-Rewrite-Answer-main\finetune-llama\run_clm_sft_with_peft-7b.py", line 307, in main
    train_dataset = build_instruction_dataset(
  File "D:\jjx\Retrieve-Rewrite-Answer-main\Retrieve-Rewrite-Answer-main\finetune-llama\build_dataset.py", line 65, in build_instruction_dataset
    raw_dataset = load_dataset("json", data_files=file, cache_dir=cache_path)
  File "C:\Users\jiaojiaxing\.conda\envs\RRA\lib\site-packages\datasets\load.py", line 2523, in load_dataset
    builder_instance = load_dataset_builder(
  File "C:\Users\jiaojiaxing\.conda\envs\RRA\lib\site-packages\datasets\load.py", line 2232, in load_dataset_builder
01/21/2024 15:27:11 - INFO - datasets.builder - Using custom data configuration default-2995dd276f7112c1
01/21/2024 15:27:11 - INFO - datasets.info - Loading Dataset Infos from C:\Users\jiaojiaxing\.conda\envs\RRA\lib\site-packages\datasets\packaged_modules\json
    builder_instance: DatasetBuilder = builder_cls(
  File "C:\Users\jiaojiaxing\.conda\envs\RRA\lib\site-packages\datasets\builder.py", line 418, in __init__
    with FileLock(lock_path):
  File "C:\Users\jiaojiaxing\.conda\envs\RRA\lib\site-packages\filelock\_api.py", line 297, in __enter__
    self.acquire()
  File "C:\Users\jiaojiaxing\.conda\envs\RRA\lib\site-packages\filelock\_api.py", line 255, in acquire
    self._acquire()
  File "C:\Users\jiaojiaxing\.conda\envs\RRA\lib\site-packages\filelock\_windows.py", line 28, in _acquire
    fd = os.open(self.lock_file, flags, self._context.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\jjx\\Retrieve-Rewrite-Answer-main\\Retrieve-Rewrite-Answer-main\\finetune-llama\\MetaQA\\dataset_dir\\dev\\_jjx_Retrieve-Rewrite-Answer-main_Retrieve-Rewrite-Answer-main_finetune-llama_MetaQA_dataset_dir_dev_json_default-2995dd276f7112c1_0.0.0_8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96.lock'

Process finished with exit code 1

运行不带--do_train和--do_eval就不会报错  正常运行   但是 不会进行训练

**Comment by Suiji12** [comment]
问题已经解决  还是datasets版本的问题

**Comment by Suiji12** [comment]
您好，请问您回复的是什么？我没有看到。
目前的问题还是loss一直为0。

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月22日 19:56 |
| 收件人 | wuyike2000/Retrieve-Rewrite-Answer ***@***.***> |
| 抄送人 | Suiji12 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [wuyike2000/Retrieve-Rewrite-Answer] 在运行run_clm_sft_with_peft-7b.py文件时，报错缺少文件：FileNotFoundError: [Errno 2] No such file or directory: _dir_dev_json_default-2995dd276f7112c1_0.0.0_8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96.lock' (Issue #6) |

Closed #6 as completed.
